version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0  
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  
      - ES_JAVA_OPTS=-Xmx512m -Xms512m  
    ports:
      - "9200:9200"  
    volumes:
      - esdata:/usr/share/elasticsearch/data  
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"  
    depends_on:
      - elasticsearch  

  

volumes:
  esdata:
    driver: local
